/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.v201608040617.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/**
 * description: LocationInput = This interface offers functions that implement the
 *   location-input functionality of a navigation system
 */
#ifndef V4_ORG_GENIVI_NAVIGATION_NAVIGATIONCORE_Location_Input_PROXY_BASE_HPP_
#define V4_ORG_GENIVI_NAVIGATION_NAVIGATIONCORE_Location_Input_PROXY_BASE_HPP_

#include <v4/org/genivi/navigation/navigationcore/LocationInput.hpp>


#include <v4/org/genivi/CommonTypes.hpp>
#include <v4/org/genivi/navigation/NavigationTypes.hpp>
#include <v4/org/genivi/navigation/navigationcore/NavigationCoreTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v4 {
namespace org {
namespace genivi {
namespace navigation {
namespace navigationcore {

class LocationInputProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, ::v4::org::genivi::navigation::navigationcore::LocationInput::AddressAttribute
    > CurrentSelectionCriterionEvent;
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, ::v4::org::genivi::navigation::navigationcore::LocationInput::SearchStatus
    > SearchStatusEvent;
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, std::string, std::string, bool
    > SpellResultEvent;
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, uint16_t, uint16_t, uint16_t, std::vector<::v4::org::genivi::navigation::navigationcore::LocationInput::Address>
    > SearchResultListEvent;
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, uint16_t
    > SearchResultListSizeChangedEvent;
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, bool, std::vector<::v4::org::genivi::navigation::navigationcore::LocationInput::AddressAttribute>, ::v4::org::genivi::navigation::navigationcore::LocationInput::Address
    > ContentUpdatedEvent;
    typedef CommonAPI::Event<
        ::v4::org::genivi::navigation::NavigationTypes::LocationHandle, std::vector<::v4::org::genivi::navigation::navigationcore::LocationInput::Address>, std::vector<::v4::org::genivi::navigation::navigationcore::LocationInput::ValidationStatus>
    > AddressValidationResultEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const ::v4::org::genivi::CommonTypes::Version&)> GetVersionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle&)> CreateLocationInputAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> DeleteLocationInputAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const LocationInput::AddressAttributeList&)> GetSupportedAddressAttributesAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> SetAddressAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> SetSelectionCriterionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> SpellAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> SearchAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> RequestListUpdateAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> SelectEntryAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const LocationInput::Address&)> GetEntryAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> ValidateAddressAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&)> ReverseGeocodeAsyncCallback;


    /**
     * description: currentSelectionCriterion = This signal notifies the SelectionCriterion for the
     *   current speller input or search.
     */
    virtual CurrentSelectionCriterionEvent& getCurrentSelectionCriterionEvent() = 0;
    /**
     * description: searchStatus = This signal updates the search status of the specified session
     */
    virtual SearchStatusEvent& getSearchStatusEvent() = 0;
    /**
     * description: spellResult = This signal notifies the result of the previous Spell method
     */
    virtual SpellResultEvent& getSpellResultEvent() = 0;
    /**
     * description: searchResultList = This signal updates the address result list (e.g. after a
     *   Search/Spell/Scroll call)
     */
    virtual SearchResultListEvent& getSearchResultListEvent() = 0;
    /**
     * description: searchResultListSizeChanged = This signal updates the size of the address
     *   result list
     */
    virtual SearchResultListSizeChangedEvent& getSearchResultListSizeChangedEvent() = 0;
    /**
     * description: contentUpdated = This signal updates the input content data for the specified
     *   session
     */
    virtual ContentUpdatedEvent& getContentUpdatedEvent() = 0;
    /**
     * description: addressValidationResult = This signal notifies the validation result of a
     *   former ValidateAddress call
     */
    virtual AddressValidationResultEvent& getAddressValidationResultEvent() = 0;

    /**
     * description: getVersion = This method returns the API version implemented by the server
     *   application
     */
    virtual void getVersion(CommonAPI::CallStatus &_internalCallStatus, ::v4::org::genivi::CommonTypes::Version &_version, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getVersionAsync(GetVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: createLocationInput = This method creates a new location input and retrieves a
     *   handle
     */
    virtual void createLocationInput(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, CommonAPI::CallStatus &_internalCallStatus, ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> createLocationInputAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, CreateLocationInputAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: deleteLocationInput = This method deletes a location input and its associated
     *   resources
     */
    virtual void deleteLocationInput(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> deleteLocationInputAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, DeleteLocationInputAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: getSupportedAddressAttributes = This method retrieves the supported address
     *   attributes
     */
    virtual void getSupportedAddressAttributes(CommonAPI::CallStatus &_internalCallStatus, LocationInput::AddressAttributeList &_addressAttributesList, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getSupportedAddressAttributesAsync(GetSupportedAddressAttributesAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: setAddress = This method sets the address to start with for the LocationInput
     *   identified by the given handle
     */
    virtual void setAddress(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const LocationInput::Address &_address, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setAddressAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const LocationInput::Address &_address, SetAddressAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: setSelectionCriterion = This method sets the selection criterion for the
     *   current speller, search input and the corresponding result-lists for the
     *   current session
     */
    virtual void setSelectionCriterion(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const LocationInput::AddressAttribute &_selectionCriterion, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setSelectionCriterionAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const LocationInput::AddressAttribute &_selectionCriterion, SetSelectionCriterionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: spell = This method sends the next spell input for the current session
     */
    virtual void spell(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const std::string &_inputCharacter, const uint16_t &_maxWindowSize, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> spellAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const std::string &_inputCharacter, const uint16_t &_maxWindowSize, SpellAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: search = This method sends the search input for the current session
     */
    virtual void search(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const std::string &_inputString, const uint16_t &_maxWindowSize, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> searchAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const std::string &_inputString, const uint16_t &_maxWindowSize, SearchAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: requestListUpdate = This method sends a request for more list elements for the
     *   current session
     */
    virtual void requestListUpdate(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const uint16_t &_offset, const uint16_t &_maxWindowSize, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> requestListUpdateAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const uint16_t &_offset, const uint16_t &_maxWindowSize, RequestListUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: selectEntry = This method triggers selection of a result list entry by index
     */
    virtual void selectEntry(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const uint16_t &_index, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> selectEntryAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const uint16_t &_index, SelectEntryAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: getEntry = This method synchronously gets the address for the given result list
     *   entry
     */
    virtual void getEntry(const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const uint16_t &_index, CommonAPI::CallStatus &_internalCallStatus, LocationInput::Address &_address, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getEntryAsync(const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const uint16_t &_index, GetEntryAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: validateAddress = This method validates an address from different sources than
     *   Navigation
     */
    virtual void validateAddress(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const LocationInput::Address &_inputAddress, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> validateAddressAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const LocationInput::Address &_inputAddress, ValidateAddressAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: reverseGeocode = This method transforms a geocoordinate into an address
     */
    virtual void reverseGeocode(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const ::v4::org::genivi::navigation::NavigationTypes::Coordinate2D &_coordinate, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> reverseGeocodeAsync(const ::v4::org::genivi::navigation::NavigationTypes::Handle &_sessionHandle, const ::v4::org::genivi::navigation::NavigationTypes::LocationHandle &_locationInputHandle, const ::v4::org::genivi::navigation::NavigationTypes::Coordinate2D &_coordinate, ReverseGeocodeAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace navigationcore
} // namespace navigation
} // namespace genivi
} // namespace org
} // namespace v4


// Compatibility
namespace v4_0 = v4;

#endif // V4_ORG_GENIVI_NAVIGATION_NAVIGATIONCORE_Location_Input_PROXY_BASE_HPP_
